name: Build Release

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Publish Release
      run: dotnet publish -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true -o app
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: MedSearchWPF-Release
        path: app/
